name: Build and Test Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master fix-github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - hello-world
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd ./${{ matrix.path }}
        go build -v

    - name: Test
      run: |
        go test -v
